[tool.poetry]
name = "planar"
version = "0.1.0"
description = ""
authors = ["Michael Zhang <mail@mzhang.io>"]

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
